// <auto-generated />
using System;
using Fiap.TechChallenge.Fase1.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fiap.TechChallenge.Fase1.Data.Migrations
{
    [DbContext(typeof(ContextTechChallenge))]
    [Migration("20241001022626_Ajuste_seed_usuario_teste")]
    partial class Ajuste_seed_usuario_teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fiap.TechChallenge.Fase1.Dominio.Entidades.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DDD")
                        .HasColumnType("INT")
                        .HasColumnName("ddd");

                    b.Property<DateTime?>("Dt_Alteracao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime?>("Dt_Exclusao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_exclusao");

                    b.Property<DateTime>("Dt_Registro")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Excluido")
                        .HasColumnType("BOOL")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(9)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_contato");

                    b.ToTable("contato", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e2db20b-c58b-4894-a079-ec02cc9b2cd3"),
                            DDD = 11,
                            Dt_Registro = new DateTime(2024, 9, 30, 23, 26, 25, 861, DateTimeKind.Local).AddTicks(741),
                            Email = "emailtestecontato@gmail.com",
                            Excluido = false,
                            Nome = "Nome Teste",
                            Telefone = "994918888"
                        },
                        new
                        {
                            Id = new Guid("b9d00018-d3e7-4e0a-b868-c354a02120ef"),
                            DDD = 11,
                            Dt_Registro = new DateTime(2024, 9, 30, 23, 26, 25, 861, DateTimeKind.Local).AddTicks(774),
                            Email = "emailtestecontatoexcluir@gmail.com",
                            Excluido = false,
                            Nome = "Nome Teste",
                            Telefone = "994918888"
                        });
                });

            modelBuilder.Entity("Fiap.TechChallenge.Fase1.Dominio.Entidades.DDDRegiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DDD")
                        .HasColumnType("INT")
                        .HasColumnName("ddd");

                    b.Property<DateTime?>("Dt_Alteracao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime?>("Dt_Exclusao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_exclusao");

                    b.Property<DateTime>("Dt_Registro")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_registro");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("estado");

                    b.Property<bool>("Excluido")
                        .HasColumnType("BOOL")
                        .HasColumnName("excluido");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("regiao");

                    b.HasKey("Id")
                        .HasName("pk_regiao");

                    b.ToTable("regiao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("945efc41-8b1b-40a2-95bf-6c950b162725"),
                            DDD = 11,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("b1bd3ea9-823a-4797-a52e-9e3e729a68a9"),
                            DDD = 12,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("75c3fc98-2b4c-44e5-9a25-634ad9bb809a"),
                            DDD = 13,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("69175ca8-fbbf-48f2-972a-bf3ae73a7488"),
                            DDD = 14,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("df4c649b-344b-4791-beac-c61a3dfc9998"),
                            DDD = 15,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("5fe41938-8359-4af6-a57f-0355e9d921e4"),
                            DDD = 16,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("f97898a7-8bc2-4fae-b8bb-a0c605eaadd8"),
                            DDD = 17,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("4ad27ba5-6174-497a-b279-b14da28afb41"),
                            DDD = 18,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("f1ab03f5-0bdf-4c7c-9df3-286eee794ef2"),
                            DDD = 19,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("9e7b1f45-e4fd-4247-95d0-f7f9bbe14133"),
                            DDD = 21,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RJ",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("77aa8753-4f4d-430b-8a68-08bb6d3d749d"),
                            DDD = 22,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RJ",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("aab3bfbd-9741-49db-ada0-9c95f3f9239c"),
                            DDD = 24,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RJ",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("4d2d6017-456e-4fc1-ae36-f5311dd748a1"),
                            DDD = 27,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "ES",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("a6f0fc31-65b7-4f66-8ae5-93a8e7fab442"),
                            DDD = 28,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "ES",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("99f29bce-250f-4d9f-9d73-f901f7c51227"),
                            DDD = 31,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MG",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("c4b73556-0941-4fc8-879c-e039431e5a1d"),
                            DDD = 32,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MG",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("f0647679-98b7-4aae-9171-0d5fbf06342f"),
                            DDD = 33,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MG",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("77f2901c-f120-466f-9e2b-3ae2aa77e2d9"),
                            DDD = 34,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MG",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("cb6b7087-db9a-4573-8847-a7f69115666a"),
                            DDD = 35,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MG",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("5f21161b-105a-4cc2-b49b-be53378c944c"),
                            DDD = 37,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MG",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("51f3699d-cd3d-46a8-b4eb-cfac58223e68"),
                            DDD = 38,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MG",
                            Excluido = false,
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("5afebcfd-4a9e-4135-8847-dd32a8c56f56"),
                            DDD = 41,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("ce5f80cd-2c7e-41b6-84b7-77f7a6371e00"),
                            DDD = 42,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SC",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("d770ed61-9503-4246-b4c6-c78465e819cf"),
                            DDD = 43,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("3f26502a-2b4b-40ca-80d8-51a2d1fabf91"),
                            DDD = 44,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("29b24f05-5229-46de-bf0a-0931d8fc03e8"),
                            DDD = 45,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("a14f6850-263c-430c-aeb9-9b53b305a459"),
                            DDD = 46,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("7a6212e9-1c9f-4789-85ad-a07fd5a6e4cc"),
                            DDD = 47,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SC",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("f299d650-31d2-4afb-b71d-3d36482e6168"),
                            DDD = 48,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SC",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("fee64940-734e-434f-bfe5-0691dd710700"),
                            DDD = 49,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SC",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("949df9f6-1c9b-4aba-81e3-fad4ffd56779"),
                            DDD = 51,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RS",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("f3ad9d9b-fa0a-4612-9781-e5d8a48a5009"),
                            DDD = 53,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RS",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("cf9c40c5-3dbf-4424-ac0c-a3b834047524"),
                            DDD = 54,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RS",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("25b5d28a-6b24-4e87-8a24-061ab1198b40"),
                            DDD = 55,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RS",
                            Excluido = false,
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("7302feb1-35df-43af-be82-0c31c82e5b10"),
                            DDD = 61,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "DF",
                            Excluido = false,
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("f7540447-94db-4635-8434-eb631d63af68"),
                            DDD = 62,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "GO",
                            Excluido = false,
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("73e18019-a0a4-42e7-955b-d82353b9dc1b"),
                            DDD = 63,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "TO",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("773992c1-2c86-4f3e-9d52-42e0895551aa"),
                            DDD = 64,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "GO",
                            Excluido = false,
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("85da55af-89c4-4e69-9d99-298a424dc61b"),
                            DDD = 65,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MT",
                            Excluido = false,
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("38123531-f326-47b5-af48-a4009c22dfd2"),
                            DDD = 66,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MT",
                            Excluido = false,
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("70e27c5c-f112-4225-9cda-4ea684dd6c0d"),
                            DDD = 67,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MS",
                            Excluido = false,
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("56c94f08-28e3-46df-8c0b-83c089f4122c"),
                            DDD = 68,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "AC",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("6e9528f2-0c41-482f-9cd2-151b2d0ecb52"),
                            DDD = 69,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RO",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("44ae8490-f379-4a1c-b277-1ef8e01bbab8"),
                            DDD = 71,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "BA",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("a6c640f1-aee4-4b66-8dff-296de5bfc52d"),
                            DDD = 73,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "BA",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("5f59f88d-ed7b-4482-acae-d54da96d65e7"),
                            DDD = 74,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "BA",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("9f467deb-f65d-459d-931d-ff63428a3763"),
                            DDD = 75,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "BA",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("a7aaec64-5ff4-4587-9e48-0d66a070ee92"),
                            DDD = 77,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "BA",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("7a655589-3fe3-4973-830a-a6cfc9095499"),
                            DDD = 79,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SE",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("81e2b2ef-35a8-4d0f-bd25-7679e585ddd0"),
                            DDD = 81,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PE",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("629fabd5-40d8-4c7e-b2f9-91349f2b9501"),
                            DDD = 82,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "AL",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("4bf83f87-0a42-432d-8437-3da34b83ebbe"),
                            DDD = 83,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PB",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("966bcf8b-9be6-4cd8-9c86-f1fc6211c96b"),
                            DDD = 84,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RN",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("34604aed-8310-472c-9e13-cfb659da064e"),
                            DDD = 85,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "CE",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("6c087922-eed8-4727-b472-4ed08a1d0c58"),
                            DDD = 86,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PI",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("1c349e5e-29e3-4d00-8f55-dab39a7bd222"),
                            DDD = 87,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PE",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("c7134408-e0c3-43d0-9ac8-63e18f52066a"),
                            DDD = 88,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "CE",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("a2026e8c-f74b-46cf-9f29-99e27b77f22a"),
                            DDD = 89,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PI",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("d1b1a026-2b61-4fdb-8233-66016108cae5"),
                            DDD = 91,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PA",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("5475d95a-2dc2-4242-b86d-db3dd0c4a7b1"),
                            DDD = 92,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "AM",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("ffac45d9-c50d-47dd-bdfb-7c0795bef62d"),
                            DDD = 93,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PA",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("9cea7340-d090-4ecb-9e4d-f90e40c4a084"),
                            DDD = 94,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PA",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("8ee883de-bf05-4770-8ee5-d70102ffd88a"),
                            DDD = 95,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "RR",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("b845fe01-827a-4a2f-a481-231391a056cd"),
                            DDD = 96,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "AP",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("ea33fb99-0b8c-4541-b92f-c0ffb668dd25"),
                            DDD = 97,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "AM",
                            Excluido = false,
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("9028279e-643c-48c5-bafa-3b2cff7a7f49"),
                            DDD = 98,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MA",
                            Excluido = false,
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("28c941f6-e641-4a02-b190-6d3f5ba48ead"),
                            DDD = 99,
                            Dt_Registro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "MA",
                            Excluido = false,
                            Regiao = "Nordeste"
                        });
                });

            modelBuilder.Entity("Fiap.TechChallenge.Fase1.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Dt_Alteracao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime?>("Dt_Exclusao")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_exclusao");

                    b.Property<DateTime>("Dt_Registro")
                        .HasColumnType("timestamp")
                        .HasColumnName("dt_registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("email");

                    b.Property<bool>("Excluido")
                        .HasColumnType("BOOL")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nome");

                    b.Property<short>("Role")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("role");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fe1b663-4356-4b2b-82e6-a0d9d7aa4eac"),
                            Dt_Registro = new DateTime(2024, 9, 30, 23, 26, 25, 861, DateTimeKind.Local).AddTicks(688),
                            Email = "admin@gmail.com",
                            Excluido = false,
                            Nome = "Administrador",
                            Role = (short)0,
                            Senha = "$2b$12$/nj7LJgiUFp32SZ9A2A98e83JwjOtWPhOLTnplHMCRQqKfqGHAmVS"
                        },
                        new
                        {
                            Id = new Guid("cfdb5869-3e32-4129-8e3e-463ef610ec94"),
                            Dt_Registro = new DateTime(2024, 9, 30, 23, 26, 25, 861, DateTimeKind.Local).AddTicks(717),
                            Email = "emailtesteusuario@gmail.com",
                            Excluido = false,
                            Nome = "Usuario",
                            Role = (short)1,
                            Senha = "$2b$12$/nj7LJgiUFp32SZ9A2A98e83JwjOtWPhOLTnplHMCRQqKfqGHAmVS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
